---
- name: "nxos.restore: copy configuration file to remote device"
  nxos_file_copy:
    local_file: "{{ _backup_manager_git_store_path }}/running.cfg"
    remote_file: "restore.cfg"

- name: "nxos.restore: replace configuration"
  nxos_config:
    replace_src: "restore.cfg"
